import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.demoblaze.com/');
  await page.getByRole('link', { name: 'Laptops' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(3).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('link', { name: 'Add to cart' }).click();
  await page.getByRole('link', { name: 'Cart', exact: true }).click();
  await page.getByText('Products Pic Title Price x').click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.getByRole('textbox', { name: 'Total: 700 Name:' }).click();
  await page.getByRole('textbox', { name: 'Total: 700 Name:' }).fill('MD ');
  await page.getByRole('textbox', { name: 'Country:' }).click();
  await page.getByRole('textbox', { name: 'Country:' }).fill('BD');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Purchase' }).click();
  await page.getByRole('dialog', { name: 'Place order' }).getByLabel('Close').click();
});

//code generated by Playwright Codegen tool, to record user actions on the browser and generate code in JavaScript.
//codegen command npx playwright codegen -0 tests/codegen.spec.jos -b chromium --target javascript
